In [1]:
import numpy as np

In [14]:
x = np.random.rand(100,10)

In [15]:
x

array([[ 0.22502197,  0.40200117,  0.58942013,  0.75001995,  0.84576123,
         0.64145228,  0.80126239,  0.76481393,  0.23791081,  0.08632398],
       [ 0.03247247,  0.68452384,  0.30062333,  0.32615017,  0.75872764,
         0.76936893,  0.79978332,  0.62597264,  0.81465976,  0.09857846],
       [ 0.09397731,  0.72412178,  0.74601478,  0.11025512,  0.35975098,
         0.07964485,  0.03193488,  0.76110304,  0.54974962,  0.65437013],
       [ 0.66533394,  0.65198935,  0.88670765,  0.15579961,  0.77905761,
         0.09649985,  0.89699718,  0.728514  ,  0.59137371,  0.00211771],
       [ 0.64624311,  0.94420657,  0.09032391,  0.22474241,  0.31138544,
         0.4350018 ,  0.76212224,  0.33645285,  0.32070895,  0.83587113],
       [ 0.38235539,  0.1239434 ,  0.6940037 ,  0.81592523,  0.73090488,
         0.81782532,  0.17782732,  0.94926263,  0.26591884,  0.27301693],
       [ 0.1008751 ,  0.92040853,  0.37867505,  0.46227346,  0.55828655,
         0.77747213,  0.11132467,  0.1989761 

In [16]:
y = x[:5, :]

In [17]:
np.may_share_memory(x, y)

True

In [18]:
y[:] = 0
y

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [19]:
x[:5, :]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

# Numpy copy

In [21]:
x = np.random.rand(100,10)
y = np.empty([5,10])
y[:] = x[:5, :]
np.may_share_memory(x, y)

False

In [22]:
x[:] = 0
print(x[:5, :])

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
